//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAsp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStok
    {
        public int UrunBarkod { get; set; }
        public string UrunIsim { get; set; }
        public Nullable<int> UrunStok { get; set; }
    
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
